In [3]:
import numpy as np

In [4]:
import pandas as pd

### Creating Arrays

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [26]:
a = np.array([3,24,234,56,2,16,34])

In [27]:
print (a)

[  3  24 234  56   2  16  34]


In [28]:
a[5]

16

In [29]:
a[5] = 49

In [30]:
print(a[5])

49


In [33]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimentional arrays

In [40]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [44]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
n[2,1]

8

In [46]:
n[1]

array([4, 5, 6])

In [49]:
n[:,1]

array([2, 5, 8])

In [54]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [59]:
#np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[50,  4],
       [90, 63],
       [79, 49],
       [39, 46],
       [ 8, 50]])

### Element-wise Operations

In [61]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [64]:
# numpy makes it very simple to perform operations on matrices and arrays, without writting for loops
#a+1
a*2
10+ (a*2)

array([10, 12, 14, 16, 18])

In [65]:
a= np.array([4,5,6])
b= np.array([5,3,2])
a + b

array([9, 8, 8])

### Comparison operations

In [66]:
a

array([4, 5, 6])

In [68]:
a>=5

array([False,  True,  True])

In [69]:
b

array([5, 3, 2])

In [70]:
a[a>b]

array([5, 6])

### Summarizing Operations

In [71]:
a

array([4, 5, 6])

In [73]:
a.max()

6

In [74]:
a.sum()

15

In [75]:
a.mean()

5.0

In [78]:
a[0] = 7

In [79]:
a

array([7, 5, 6])

In [80]:
a.sort()
a

array([5, 6, 7])